### PR TITLE
Drop Node <12, ESM-only, tooling updates

### LINKED ISSUE #32: Potential Breaking Change Queue
- Drop node 8 support
  - eslint@7
  - @typescript-eslint/*@3 [source](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0) (although it's fine so far)
- [Package entry points](https://nodejs.org/docs/latest-v12.x/api/esm.html#esm_package_entry_points) - node >= 12?
- Ship ESM - (not a breaking change if dual-shipping)

### PR DESCRIPTION
**Pull request by tchetwin**
Fixes #32

https://node.green indicates that we can use #private instance fields with the required node >= 12.20 engine.

typedoc@beta is required in conjunction with typescript@4.3.x

### CODE REVIEW

**Comment by tchetwin** [comment]
In order to rebase this we need to wait for an upstream patch to TypeDoc to be compatible with TypeScript 4.3.x. No rush! 👍

**Review by ldarbi — APPROVED** [review]
lgtm

**Review by ldarbi — DISMISSED** [review]

**Comment by tchetwin** [comment]
Rebased to include recent GitHub Actions swap

**Comment by tchetwin** [comment]
Will address in multiple PRs

**Pull request closed without merging**
