### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by tchetwin**

### CODE REVIEW

**Comment by tchetwin** [comment]
Supersedes #42

**Review by kpfleming — DISMISSED** [review]
Looks great! I especially like the "on - release - created" trigger for publishing, I hadn't realized that was possible.

**Comment by tchetwin** [comment]
I've removed the Travis configuration. Consequently the _Required_ "Travis CI" bot won't run and this PR will not receive "Green CI".

**Comment by kpfleming** [comment]
I've marked the Travis-CI as no longer 'required'. I'll make the Actions checks 'required' once they have settled down.

**Review by rricard — APPROVED** [review]

**Pull request merged**
